---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - crd.lagoon.sh
  resources:
  - lagoonbuilds
  - lagoontasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.lagoon.sh
  resources:
  - lagoonbuilds/status
  - lagoontasks/status
  verbs:
  - get
  - patch
  - update
