kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."172.17.0.1:5000"]
    endpoint = ["http://172.17.0.1:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."harbor.172.17.0.1.nip.io:32080"]
    endpoint = ["http://harbor.172.17.0.1.nip.io:32080"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor.172.17.0.1.nip.io:32443".tls]
    insecure_skip_verify = true
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32080
    hostPort: 32080
    protocol: TCP
  - containerPort: 32443
    hostPort: 32443
    protocol: TCP